// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PluginInfo describes a loaded plugin for the settings UI.
 */
export class PluginInfo {
    /**
     * Creates a new PluginInfo instance.
     * @param {Partial<PluginInfo>} [$$source = {}] - The source object to create the PluginInfo.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Version"] = "";
        }
        if (!("Description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Description"] = "";
        }
        if (!("Permissions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["Permissions"] = [];
        }
        if (!("IconPath" in $$source)) {
            /**
             * absolute manifest-icon path ("" when none)
             * @member
             * @type {string}
             */
            this["IconPath"] = "";
        }
        if (!("Disabled" in $$source)) {
            /**
             * user- or auto-disabled
             * @member
             * @type {boolean}
             */
            this["Disabled"] = false;
        }
        if (!("AutoDisabled" in $$source)) {
            /**
             * disabled by the 3-strike timeout rule
             * @member
             * @type {boolean}
             */
            this["AutoDisabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginInfo}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Permissions" in $$parsedSource) {
            $$parsedSource["Permissions"] = $$createField4_0($$parsedSource["Permissions"]);
        }
        return new PluginInfo(/** @type {Partial<PluginInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
