// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Author is the manifest author block.
 */
export class Author {
    /**
     * Creates a new Author instance.
     * @param {Partial<Author>} [$$source = {}] - The source object to create the Author.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["url"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Author instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Author}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Author(/** @type {Partial<Author>} */($$parsedSource));
    }
}

/**
 * PluginInfo describes a plugin for the settings UI, combining local and remote metadata.
 */
export class PluginInfo {
    /**
     * Creates a new PluginInfo instance.
     * @param {Partial<PluginInfo>} [$$source = {}] - The source object to create the PluginInfo.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Version"] = "";
        }
        if (!("Description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Description"] = "";
        }
        if (!("Permissions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["Permissions"] = [];
        }
        if (!("Author" in $$source)) {
            /**
             * @member
             * @type {Author}
             */
            this["Author"] = (new Author());
        }
        if (!("IconPath" in $$source)) {
            /**
             * absolute manifest-icon path ("" when none)
             * @member
             * @type {string}
             */
            this["IconPath"] = "";
        }
        if (!("IconURL" in $$source)) {
            /**
             * remote icon URL for registry plugins
             * @member
             * @type {string}
             */
            this["IconURL"] = "";
        }
        if (!("Disabled" in $$source)) {
            /**
             * user- or auto-disabled
             * @member
             * @type {boolean}
             */
            this["Disabled"] = false;
        }
        if (!("AutoDisabled" in $$source)) {
            /**
             * disabled by the 3-strike timeout rule
             * @member
             * @type {boolean}
             */
            this["AutoDisabled"] = false;
        }
        if (!("Status" in $$source)) {
            /**
             * @member
             * @type {PluginStatus}
             */
            this["Status"] = PluginStatus.$zero;
        }
        if (!("DownloadURL" in $$source)) {
            /**
             * URL for downloading from registry
             * @member
             * @type {string}
             */
            this["DownloadURL"] = "";
        }
        if (!("Category" in $$source)) {
            /**
             * Plugin category for marketplace
             * @member
             * @type {string}
             */
            this["Category"] = "";
        }
        if (!("Keywords" in $$source)) {
            /**
             * Search keywords
             * @member
             * @type {string[]}
             */
            this["Keywords"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginInfo}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType1;
        const $$createField13_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Permissions" in $$parsedSource) {
            $$parsedSource["Permissions"] = $$createField4_0($$parsedSource["Permissions"]);
        }
        if ("Author" in $$parsedSource) {
            $$parsedSource["Author"] = $$createField5_0($$parsedSource["Author"]);
        }
        if ("Keywords" in $$parsedSource) {
            $$parsedSource["Keywords"] = $$createField13_0($$parsedSource["Keywords"]);
        }
        return new PluginInfo(/** @type {Partial<PluginInfo>} */($$parsedSource));
    }
}

/**
 * PluginStats represents plugin statistics.
 */
export class PluginStats {
    /**
     * Creates a new PluginStats instance.
     * @param {Partial<PluginStats>} [$$source = {}] - The source object to create the PluginStats.
     */
    constructor($$source = {}) {
        if (!("downloads" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["downloads"] = 0;
        }
        if (!("rating" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rating"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginStats(/** @type {Partial<PluginStats>} */($$parsedSource));
    }
}

/**
 * PluginStatus represents the installation and enablement state of a plugin.
 * @readonly
 * @enum {string}
 */
export const PluginStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * Available in registry but not installed
     */
    StatusNotInstalled: "not_installed",

    /**
     * Installed but disabled
     */
    StatusInstalled: "installed",

    /**
     * Installed and enabled
     */
    StatusEnabled: "enabled",
};

/**
 * RemotePlugin represents a plugin available for installation from the registry.
 */
export class RemotePlugin {
    /**
     * Creates a new RemotePlugin instance.
     * @param {Partial<RemotePlugin>} [$$source = {}] - The source object to create the RemotePlugin.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {Author}
             */
            this["author"] = (new Author());
        }
        if (!("download_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["download_url"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["icon_url"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Date | undefined}
             */
            this["updated_at"] = undefined;
        }
        if (!("minHostVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["minHostVersion"] = "";
        }
        if (!("permissions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["permissions"] = [];
        }
        if (!("platforms" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["platforms"] = [];
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("keywords" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["keywords"] = [];
        }
        if (!("stats" in $$source)) {
            /**
             * @member
             * @type {PluginStats}
             */
            this["stats"] = (new PluginStats());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemotePlugin instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RemotePlugin}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        const $$createField7_0 = $Create.DateFromTime;
        const $$createField9_0 = $$createType0;
        const $$createField10_0 = $$createType0;
        const $$createField12_0 = $$createType0;
        const $$createField13_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("author" in $$parsedSource) {
            $$parsedSource["author"] = $$createField4_0($$parsedSource["author"]);
        }
        if ("updated_at" in $$parsedSource) {
            $$parsedSource["updated_at"] = $$createField7_0($$parsedSource["updated_at"]);
        }
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField9_0($$parsedSource["permissions"]);
        }
        if ("platforms" in $$parsedSource) {
            $$parsedSource["platforms"] = $$createField10_0($$parsedSource["platforms"]);
        }
        if ("keywords" in $$parsedSource) {
            $$parsedSource["keywords"] = $$createField12_0($$parsedSource["keywords"]);
        }
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField13_0($$parsedSource["stats"]);
        }
        return new RemotePlugin(/** @type {Partial<RemotePlugin>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Author.createFrom;
const $$createType2 = PluginStats.createFrom;
