// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SearchService is bound to the frontend by Wails. Search feeds the result
 * list; Launch activates a result from the most recent Search and records
 * usage (frecency); the plugin methods back the settings window.
 * 
 * The engine, store and providers are constructed lazily in ServiceStartup:
 * the single-instance guard inside application.New must get the chance to
 * exit a duplicate process before this service contends on the bbolt lock.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../internal/core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugin$0 from "../internal/plugin/models.js";

/**
 * Browsers lists installed browser names usable as the external browser
 * (empty on platforms without browser detection).
 * @returns {$CancellablePromise<string[]>}
 */
export function Browsers() {
    return $Call.ByID(1142220318).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ExternalBrowser returns the configured external browser for open-url
 * actions ("" = system default).
 * @returns {$CancellablePromise<string>}
 */
export function ExternalBrowser() {
    return $Call.ByID(504328536);
}

/**
 * Launch activates the result with the given ID (from the last Search),
 * records usage and hides the summon window.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Launch(id) {
    return $Call.ByID(1704679484, id);
}

/**
 * Plugins returns every loaded plugin (including disabled ones) for the
 * settings window.
 * @returns {$CancellablePromise<plugin$0.PluginInfo[]>}
 */
export function Plugins() {
    return $Call.ByID(444198097).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * RevealPluginsFolder opens the plugins directory in Finder (created on
 * demand), the install/uninstall entry point alongside the settings list.
 * @returns {$CancellablePromise<void>}
 */
export function RevealPluginsFolder() {
    return $Call.ByID(881473702);
}

/**
 * RunAction dispatches a plugin row (command or callback) from the last
 * Search to its plugin and returns the secondary result list. Rows whose
 * actions are open-url/copy keep flowing through Launch: the returned rows
 * are merged into the same session cache, so activating them works with no
 * extra plumbing. An empty list means "nothing to show" (the frontend hides
 * the window).
 * @param {string} id
 * @returns {$CancellablePromise<core$0.SearchResult[]>}
 */
export function RunAction(id) {
    return $Call.ByID(3268022454, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * Search runs the engine for query and caches the results for Launch.
 * @param {string} query
 * @returns {$CancellablePromise<core$0.SearchResult[]>}
 */
export function Search(query) {
    return $Call.ByID(2004525483, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * SetExternalBrowser sets the external browser ("" = system default); the
 * name must be one of Browsers().
 * @param {string} app
 * @returns {$CancellablePromise<void>}
 */
export function SetExternalBrowser(app) {
    return $Call.ByID(2443523026, app);
}

/**
 * SetPluginEnabled enables or disables a plugin and persists the choice.
 * @param {string} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetPluginEnabled(id, enabled) {
    return $Call.ByID(2582656035, id, enabled);
}

/**
 * Version returns the Kyvro application version.
 * @returns {$CancellablePromise<string>}
 */
export function Version() {
    return $Call.ByID(2173289165);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = plugin$0.PluginInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = core$0.SearchResult.createFrom;
const $$createType4 = $Create.Array($$createType3);
