// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SearchService is bound to the frontend by Wails. Search feeds the result
 * list; Execute activates a result (or one of its secondary actions) from
 * the most recent Search and records usage (frecency); the plugin and
 * folder methods back the settings window.
 * 
 * The engine, store and providers are constructed lazily in ServiceStartup:
 * the single-instance guard inside application.New must get the chance to
 * exit a duplicate process before this service contends on the bbolt lock.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../internal/core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugin$0 from "../internal/plugin/models.js";

/**
 * AddFolderSource registers and synchronously scans a new root.
 * @param {string} path
 * @param {number} maxDepth
 * @returns {$CancellablePromise<core$0.FolderSource>}
 */
export function AddFolderSource(path, maxDepth) {
    return $Call.ByID(3442979147, path, maxDepth).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AddSnippet adds a new text snippet.
 * @param {string} trigger
 * @param {string} replacement
 * @returns {$CancellablePromise<void>}
 */
export function AddSnippet(trigger, replacement) {
    return $Call.ByID(807125279, trigger, replacement);
}

/**
 * AllPlugins combines installed and available plugins for the settings UI.
 * @returns {$CancellablePromise<plugin$0.PluginInfo[]>}
 */
export function AllPlugins() {
    return $Call.ByID(845651830).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * AvailablePlugins fetches the list of plugins available from the official registry.
 * @returns {$CancellablePromise<plugin$0.RemotePlugin[]>}
 */
export function AvailablePlugins() {
    return $Call.ByID(1804721074).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * Browsers lists installed browser names usable as the external browser
 * (empty on platforms without browser detection).
 * @returns {$CancellablePromise<string[]>}
 */
export function Browsers() {
    return $Call.ByID(1142220318).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Execute activates the result with the given ID (from the last Search).
 * An empty actionID runs the PrimaryAction; otherwise the ActionItem with
 * the matching ID runs. Plugin actions return a secondary result list
 * (merged into the session cache for further activation); every terminal
 * action returns nil, which the UI treats as "hide the window". Usage is
 * recorded against the result ID on success.
 * @param {string} id
 * @param {string} actionID
 * @returns {$CancellablePromise<core$0.SearchResult[]>}
 */
export function Execute(id, actionID) {
    return $Call.ByID(2894020374, id, actionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ExternalBrowser returns the configured external browser for open-url
 * actions ("" = system default).
 * @returns {$CancellablePromise<string>}
 */
export function ExternalBrowser() {
    return $Call.ByID(504328536);
}

/**
 * FolderSources lists every configured folder source with scan status.
 * @returns {$CancellablePromise<core$0.FolderSourceInfo[]>}
 */
export function FolderSources() {
    return $Call.ByID(1684839075).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * InstallPlugin installs a plugin from the official registry by ID.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function InstallPlugin(id) {
    return $Call.ByID(1844346045, id);
}

/**
 * PickFolderSourcePath opens the native directory chooser and returns the
 * selected path. An empty string with a nil error means the user cancelled;
 * no configuration is written here.
 * @returns {$CancellablePromise<string>}
 */
export function PickFolderSourcePath() {
    return $Call.ByID(3139331788);
}

/**
 * Plugins returns every loaded plugin (including disabled ones) for the
 * settings window.
 * @returns {$CancellablePromise<plugin$0.PluginInfo[]>}
 */
export function Plugins() {
    return $Call.ByID(444198097).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * RefreshAllFolderSources rescans every enabled source.
 * @returns {$CancellablePromise<void>}
 */
export function RefreshAllFolderSources() {
    return $Call.ByID(3858442937);
}

/**
 * RefreshFolderSource rescans one source.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RefreshFolderSource(id) {
    return $Call.ByID(2530920235, id);
}

/**
 * RemoveFolderSource deletes a source and its index entries.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveFolderSource(id) {
    return $Call.ByID(1985581934, id);
}

/**
 * RemoveSnippet removes a text snippet by trigger.
 * @param {string} trigger
 * @returns {$CancellablePromise<void>}
 */
export function RemoveSnippet(trigger) {
    return $Call.ByID(2574413044, trigger);
}

/**
 * RequestSnippetAccessibility asks macOS to grant Accessibility permission to
 * the current Kyvro process.
 * @returns {$CancellablePromise<void>}
 */
export function RequestSnippetAccessibility() {
    return $Call.ByID(1927811739);
}

/**
 * RevealPluginsFolder opens the plugins directory in Finder (created on
 * demand), the install/uninstall entry point alongside the settings list.
 * @returns {$CancellablePromise<void>}
 */
export function RevealPluginsFolder() {
    return $Call.ByID(881473702);
}

/**
 * Search runs the engine for query and caches the results for Launch.
 * @param {string} query
 * @returns {$CancellablePromise<core$0.SearchResult[]>}
 */
export function Search(query) {
    return $Call.ByID(2004525483, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * SetExternalBrowser sets the external browser ("" = system default); the
 * name must be one of Browsers().
 * @param {string} app
 * @returns {$CancellablePromise<void>}
 */
export function SetExternalBrowser(app) {
    return $Call.ByID(2443523026, app);
}

/**
 * SetFolderSourceEnabled toggles a source without dropping its cache.
 * @param {string} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetFolderSourceEnabled(id, enabled) {
    return $Call.ByID(804849789, id, enabled);
}

/**
 * SetPluginEnabled enables or disables a plugin and persists the choice.
 * @param {string} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetPluginEnabled(id, enabled) {
    return $Call.ByID(2582656035, id, enabled);
}

/**
 * SetSnippetEnabled enables or disables a snippet.
 * @param {string} trigger
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetSnippetEnabled(trigger, enabled) {
    return $Call.ByID(1740263623, trigger, enabled);
}

/**
 * SetSnippetsEnabled enables or disables text expansion globally.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetSnippetsEnabled(enabled) {
    return $Call.ByID(166999392, enabled);
}

/**
 * SnippetAccessibilityGranted reports whether the current Kyvro process has
 * macOS Accessibility permission required for global text expansion.
 * @returns {$CancellablePromise<boolean>}
 */
export function SnippetAccessibilityGranted() {
    return $Call.ByID(556355039);
}

/**
 * Snippets returns all configured text snippets.
 * @returns {$CancellablePromise<core$0.Snippet[]>}
 */
export function Snippets() {
    return $Call.ByID(20510241).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * SnippetsEnabled checks if text expansion is globally enabled.
 * @returns {$CancellablePromise<boolean>}
 */
export function SnippetsEnabled() {
    return $Call.ByID(2161103978);
}

/**
 * UninstallPlugin removes an installed plugin by ID.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function UninstallPlugin(id) {
    return $Call.ByID(1309368692, id);
}

/**
 * Version returns the Kyvro application version.
 * @returns {$CancellablePromise<string>}
 */
export function Version() {
    return $Call.ByID(2173289165);
}

// Private type creation functions
const $$createType0 = core$0.FolderSource.createFrom;
const $$createType1 = plugin$0.PluginInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = plugin$0.RemotePlugin.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = core$0.SearchResult.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = core$0.FolderSourceInfo.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = core$0.Snippet.createFrom;
const $$createType11 = $Create.Array($$createType10);
