// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Action is the executable payload attached to a search result.
 */
export class Action {
    /**
     * Creates a new Action instance.
     * @param {Partial<Action>} [$$source = {}] - The source object to create the Action.
     */
    constructor($$source = {}) {
        if (!("Kind" in $$source)) {
            /**
             * @member
             * @type {ActionKind}
             */
            this["Kind"] = ActionKind.$zero;
        }
        if (!("Arg" in $$source)) {
            /**
             * Arg is the app path (ActionLaunchApp) or URL (ActionOpenURL).
             * @member
             * @type {string}
             */
            this["Arg"] = "";
        }
        if (!("PluginID" in $$source)) {
            /**
             * PluginID identifies the target plugin (ActionPlugin only).
             * @member
             * @type {string}
             */
            this["PluginID"] = "";
        }
        if (!("ActionID" in $$source)) {
            /**
             * ActionID is the plugin-defined command or callback id
             * (ActionPlugin only).
             * @member
             * @type {string}
             */
            this["ActionID"] = "";
        }
        if (!("Args" in $$source)) {
            /**
             * Args are opaque arguments passed through to the plugin
             * (ActionPlugin only).
             * @member
             * @type {string[]}
             */
            this["Args"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Action instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Action}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Args" in $$parsedSource) {
            $$parsedSource["Args"] = $$createField4_0($$parsedSource["Args"]);
        }
        return new Action(/** @type {Partial<Action>} */($$parsedSource));
    }
}

/**
 * ActionKind describes what to do when a result is activated.
 * @readonly
 * @enum {number}
 */
export const ActionKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * ActionLaunchApp launches a macOS application by path.
     */
    ActionLaunchApp: 0,

    /**
     * ActionOpenURL opens a URL in the default browser.
     */
    ActionOpenURL: 1,

    /**
     * ActionCopyText copies Arg to the clipboard (calculator results).
     */
    ActionCopyText: 2,

    /**
     * ActionPlugin dispatches to a plugin (commands and callback actions).
     * Executed via the plugin manager, never directly by the host.
     */
    ActionPlugin: 3,
};

/**
 * SearchResult is a single row in the launcher UI.
 */
export class SearchResult {
    /**
     * Creates a new SearchResult instance.
     * @param {Partial<SearchResult>} [$$source = {}] - The source object to create the SearchResult.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * ID uniquely identifies the result within a search session
             * (app ID for apps, "web:<query>" for the fallback entry).
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("Title" in $$source)) {
            /**
             * Title is the primary label.
             * @member
             * @type {string}
             */
            this["Title"] = "";
        }
        if (!("Subtitle" in $$source)) {
            /**
             * Subtitle is a secondary, dimmed label (e.g. app path).
             * @member
             * @type {string}
             */
            this["Subtitle"] = "";
        }
        if (!("Action" in $$source)) {
            /**
             * Action is executed when the user activates the result.
             * @member
             * @type {Action}
             */
            this["Action"] = (new Action());
        }
        if (!("Score" in $$source)) {
            /**
             * Score drives ordering; higher sorts first. Populated by the engine.
             * @member
             * @type {number}
             */
            this["Score"] = 0;
        }
        if (!("IconPath" in $$source)) {
            /**
             * IconPath is the icon file path rendered by the UI (apps only);
             * empty results fall back to a monogram.
             * @member
             * @type {string}
             */
            this["IconPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Action" in $$parsedSource) {
            $$parsedSource["Action"] = $$createField3_0($$parsedSource["Action"]);
        }
        return new SearchResult(/** @type {Partial<SearchResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Action.createFrom;
